# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 70801812ca212ef700c7eb1b5143857cb946901ca0b681ddfef74ea70e6c53ddbb869fcc2eacea15893ae0fafbf9bbcd800bdcdffb39d07183af353c8043fa9f

test:
  secret_key_base: f20ad163ce7d75ae5bde1812130e080233be4f37cf5e9c38509896332dec9ab5848dc1744b4ba581a1d3c919aa5ebbb3450b256567c3ed0120bcf2bf8a7bb30b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
